using Microsoft.EntityFrameworkCore.Migrations;
using System;
using System.Collections.Generic;
using BackEnd.Data;
using BackEnd.Model;

namespace BackEnd.Migrations
{
    public partial class SeedMigration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            using (var candidatoContext = new CandidatoContext())
            {
                candidatoContext.Candidatos.AddRange(Candidatos());
                candidatoContext.Candidatos.AddRange(Candidatos());
                candidatoContext.Candidatos.AddRange(Candidatos());
                candidatoContext.Candidatos.AddRange(Candidatos());
                candidatoContext.Candidatos.AddRange(Candidatos());
                candidatoContext.SaveChanges();
            }
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            using (var candidatoContext = new CandidatoContext())
            {
                candidatoContext.RemoveRange(candidatoContext.Candidatos);
                candidatoContext.SaveChanges();
            }
        }

        private IEnumerable<Candidato> Candidatos()
        {
            return new List<Candidato>()
            {
                new Candidato()
                {
                    Email = "gjpeixer@gmail.com",
                    Nome = "Glaicon Peixer",
                    Skype = "glaiconsc",
                    Telefone = "33569250",
                    Linkedin = "https://www.linkedin.com/in/glaicon-peixer/",
                    Cidade = "Blumenau",
                    Estado = "SC",
                    Portfolio = "glaicon.peixer.com",
                    Disponibilidade = TipoDisponibilidade.AteOitoHoras | TipoDisponibilidade.MaisDeOitoHoras,
                    HorarioDeTrabalho = TipoHorarioDeTrabalho.Noite | TipoHorarioDeTrabalho.Madrugada |
                                        TipoHorarioDeTrabalho.Tarde,
                    PretensaoSalarial = 2.50,
                    ConhecimentoEmIonic = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAndroid = TipoNivelConhecimento.Medio,
                    ConhecimentoEmIOS = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmHtml = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmCss = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmBoostrap = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmJQuery = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAngularJS = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJava = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAspNetMvc = TipoNivelConhecimento.Senior,
                    ConhecimentoEmC = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCPlusPlus = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCake = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmDJango = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmMajento = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPHP = TipoNivelConhecimento.Medio,
                    ConhecimentoEmWordpress = TipoNivelConhecimento.Medio,
                    ConhecimentoEmPython = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmRuby = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSQLServer = TipoNivelConhecimento.Medio,
                    ConhecimentoEmMySql = TipoNivelConhecimento.Medio,
                    ConhecimentoEmSalesforce = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPhotoshop = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmIllustrator = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSEO = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmOutroFramework = "Laravel - Bom",
                    LinkCrud = "https://github.com/Peixer/Easy_Crud"
                },
                new Candidato()
                {
                    Email = "leticia@gmail.com",
                    Nome = "Leticia Pires",
                    Skype = "letpires",
                    Telefone = "33285459",
                    Linkedin = "https://www.linkedin.com/in/letpires/",
                    Cidade = "Blumenau",
                    Estado = "SC",
                    Portfolio = "letpires.peixer.com",
                    Disponibilidade = TipoDisponibilidade.AteSeisHoras | TipoDisponibilidade.AteQuatroHoras,
                    HorarioDeTrabalho = TipoHorarioDeTrabalho.Manha | TipoHorarioDeTrabalho.Tarde |
                                        TipoHorarioDeTrabalho.Noite,
                    PretensaoSalarial = 1222.50,
                    ConhecimentoEmIonic = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmAndroid = TipoNivelConhecimento.Senior,
                    ConhecimentoEmIOS = TipoNivelConhecimento.Senior,
                    ConhecimentoEmHtml = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmCss = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmBoostrap = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJQuery = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAngularJS = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJava = TipoNivelConhecimento.Senior,
                    ConhecimentoEmAspNetMvc = TipoNivelConhecimento.Senior,
                    ConhecimentoEmC = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCPlusPlus = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCake = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmDJango = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmMajento = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPHP = TipoNivelConhecimento.Senior,
                    ConhecimentoEmWordpress = TipoNivelConhecimento.Senior,
                    ConhecimentoEmPython = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmRuby = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSQLServer = TipoNivelConhecimento.Medio,
                    ConhecimentoEmMySql = TipoNivelConhecimento.Medio,
                    ConhecimentoEmSalesforce = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPhotoshop = TipoNivelConhecimento.Medio,
                    ConhecimentoEmIllustrator = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSEO = TipoNivelConhecimento.Medio,
                    LinkCrud = "https://github.com/Peixer/Easy_Crud"
                },
                new Candidato()
                {
                    Email = "lucas@gmail.com",
                    Nome = "Lucas",
                    Skype = "lukitas",
                    Telefone = "33256969",
                    Linkedin = "https://www.linkedin.com/in/lucas/",
                    Cidade = "Navegantes",
                    Estado = "SC",
                    Portfolio = "lucas.peixer.com",
                    Disponibilidade = TipoDisponibilidade.FinaisDeSemana | TipoDisponibilidade.AteQuatroHoras,
                    HorarioDeTrabalho = TipoHorarioDeTrabalho.Manha | TipoHorarioDeTrabalho.Noite,
                    PretensaoSalarial = 12000.00,
                    ConhecimentoEmIonic = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmAndroid = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmIOS = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmHtml = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmCss = TipoNivelConhecimento.Senior,
                    ConhecimentoEmBoostrap = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJQuery = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAngularJS = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmJava = TipoNivelConhecimento.Senior,
                    ConhecimentoEmAspNetMvc = TipoNivelConhecimento.Senior,
                    ConhecimentoEmC = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCPlusPlus = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCake = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmDJango = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmMajento = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPHP = TipoNivelConhecimento.Senior,
                    ConhecimentoEmWordpress = TipoNivelConhecimento.Senior,
                    ConhecimentoEmPython = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmRuby = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSQLServer = TipoNivelConhecimento.Medio,
                    ConhecimentoEmMySql = TipoNivelConhecimento.Senior,
                    ConhecimentoEmSalesforce = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPhotoshop = TipoNivelConhecimento.Medio,
                    ConhecimentoEmIllustrator = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSEO = TipoNivelConhecimento.Medio,
                    LinkCrud = "https://github.com/Peixer/Easy_Crud"
                },
                new Candidato()
                {
                    Email = "daniel@gmail.com",
                    Nome = "Daniel",
                    Skype = "DanielSC",
                    Telefone = "335978",
                    Linkedin = "https://www.linkedin.com/in/daniel/",
                    Cidade = "Indaial",
                    Estado = "SC",
                    Portfolio = "daniel.peixer.com",
                    Disponibilidade = TipoDisponibilidade.AteQuatroHoras,
                    HorarioDeTrabalho = TipoHorarioDeTrabalho.Madrugada | TipoHorarioDeTrabalho.Noite,
                    PretensaoSalarial = 5000.00,
                    ConhecimentoEmIonic = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmAndroid = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmIOS = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmHtml = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmCss = TipoNivelConhecimento.Senior,
                    ConhecimentoEmBoostrap = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJQuery = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAngularJS = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmJava = TipoNivelConhecimento.Senior,
                    ConhecimentoEmAspNetMvc = TipoNivelConhecimento.Senior,
                    ConhecimentoEmC = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCPlusPlus = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCake = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmDJango = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmMajento = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPHP = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmWordpress = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPython = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmRuby = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmSQLServer = TipoNivelConhecimento.Medio,
                    ConhecimentoEmMySql = TipoNivelConhecimento.Senior,
                    ConhecimentoEmSalesforce = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmPhotoshop = TipoNivelConhecimento.Medio,
                    ConhecimentoEmIllustrator = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSEO = TipoNivelConhecimento.Medio,
                    LinkCrud = "https://github.com/Peixer/Easy_Crud"
                },
                new Candidato()
                {
                    Email = "fernando@gmail.com",
                    Nome = "Fernando",
                    Skype = "fernandoNavega",
                    Telefone = "33257069",
                    Linkedin = "https://www.linkedin.com/in/fernando/",
                    Cidade = "Navegantes",
                    Estado = "SC",
                    Portfolio = "fernando.peixer.com",
                    Disponibilidade = TipoDisponibilidade.FinaisDeSemana,
                    HorarioDeTrabalho = TipoHorarioDeTrabalho.Manha | TipoHorarioDeTrabalho.Noite,
                    PretensaoSalarial = 12000.00,
                    ConhecimentoEmIonic = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmAndroid = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmIOS = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmHtml = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmCss = TipoNivelConhecimento.Medio,
                    ConhecimentoEmBoostrap = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJQuery = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAngularJS = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmJava = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAspNetMvc = TipoNivelConhecimento.Medio,
                    ConhecimentoEmC = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCPlusPlus = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCake = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmDJango = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmMajento = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPHP = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmWordpress = TipoNivelConhecimento.Senior,
                    ConhecimentoEmPython = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmRuby = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSQLServer = TipoNivelConhecimento.Medio,
                    ConhecimentoEmMySql = TipoNivelConhecimento.Senior,
                    ConhecimentoEmSalesforce = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPhotoshop = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmIllustrator = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSEO = TipoNivelConhecimento.Medio,
                    LinkCrud = "https://github.com/Peixer/Easy_Crud"
                },
                new Candidato()
                {
                    Email = "renan@gmail.com",
                    Nome = "Renan",
                    Skype = "renan",
                    Telefone = "33257172",
                    Linkedin = "https://www.linkedin.com/in/renan/",
                    Cidade = "Gaspar",
                    Estado = "SC",
                    Portfolio = "renan.peixer.com",
                    Disponibilidade = TipoDisponibilidade.AteOitoHoras | TipoDisponibilidade.AteQuatroHoras,
                    HorarioDeTrabalho = TipoHorarioDeTrabalho.Noite,
                    PretensaoSalarial = 6000.00,
                    ConhecimentoEmIonic = TipoNivelConhecimento.Senior,
                    ConhecimentoEmAndroid = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmIOS = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmHtml = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmCss = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmBoostrap = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJQuery = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAngularJS = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmJava = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmAspNetMvc = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmC = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCPlusPlus = TipoNivelConhecimento.Senior,
                    ConhecimentoEmCake = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmDJango = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmMajento = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPHP = TipoNivelConhecimento.Senior,
                    ConhecimentoEmWordpress = TipoNivelConhecimento.Senior,
                    ConhecimentoEmPython = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmRuby = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSQLServer = TipoNivelConhecimento.Medio,
                    ConhecimentoEmMySql = TipoNivelConhecimento.Senior,
                    ConhecimentoEmSalesforce = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPhotoshop = TipoNivelConhecimento.Medio,
                    ConhecimentoEmIllustrator = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSEO = TipoNivelConhecimento.Medio,
                    LinkCrud = "https://github.com/Peixer/Easy_Crud"
                },
                new Candidato()
                {
                    Email = "gabriel@gmail.com",
                    Nome = "Gabriel",
                    Skype = "gabriel",
                    Telefone = "33256969",
                    Linkedin = "https://www.linkedin.com/in/gabriel/",
                    Cidade = "Pomerode",
                    Estado = "SC",
                    Portfolio = "gabriel.peixer.com",
                    Disponibilidade = TipoDisponibilidade.FinaisDeSemana | TipoDisponibilidade.AteOitoHoras |
                                      TipoDisponibilidade.MaisDeOitoHoras,
                    HorarioDeTrabalho = TipoHorarioDeTrabalho.Manha | TipoHorarioDeTrabalho.Noite |
                                        TipoHorarioDeTrabalho.Comercial,
                    PretensaoSalarial = 2000.00,
                    ConhecimentoEmIonic = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmAndroid = TipoNivelConhecimento.Senior,
                    ConhecimentoEmIOS = TipoNivelConhecimento.Senior,
                    ConhecimentoEmHtml = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmCss = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmBoostrap = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJQuery = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAngularJS = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmJava = TipoNivelConhecimento.Senior,
                    ConhecimentoEmAspNetMvc = TipoNivelConhecimento.Senior,
                    ConhecimentoEmC = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCPlusPlus = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCake = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmDJango = TipoNivelConhecimento.Medio,
                    ConhecimentoEmMajento = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPHP = TipoNivelConhecimento.Medio,
                    ConhecimentoEmWordpress = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPython = TipoNivelConhecimento.Senior,
                    ConhecimentoEmRuby = TipoNivelConhecimento.Medio,
                    ConhecimentoEmSQLServer = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmMySql = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSalesforce = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPhotoshop = TipoNivelConhecimento.Medio,
                    ConhecimentoEmIllustrator = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSEO = TipoNivelConhecimento.Medio,
                    LinkCrud = "https://github.com/Peixer/Easy_Crud"
                },
                new Candidato()
                {
                    Email = "maria@gmail.com",
                    Nome = "Maria",
                    Skype = "maria",
                    Telefone = "665978",
                    Linkedin = "https://www.linkedin.com/in/maria/",
                    Cidade = "Itajai",
                    Estado = "SC",
                    Portfolio = "maria.peixer.com",
                    Disponibilidade = TipoDisponibilidade.AteOitoHoras | TipoDisponibilidade.MaisDeOitoHoras,
                    HorarioDeTrabalho = TipoHorarioDeTrabalho.Manha | TipoHorarioDeTrabalho.Noite |
                                        TipoHorarioDeTrabalho.Comercial,
                    PretensaoSalarial = 5000.00,
                    ConhecimentoEmIonic = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmAndroid = TipoNivelConhecimento.Senior,
                    ConhecimentoEmIOS = TipoNivelConhecimento.Senior,
                    ConhecimentoEmHtml = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmCss = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmBoostrap = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJQuery = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAngularJS = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmJava = TipoNivelConhecimento.Senior,
                    ConhecimentoEmAspNetMvc = TipoNivelConhecimento.Senior,
                    ConhecimentoEmC = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCPlusPlus = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCake = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmDJango = TipoNivelConhecimento.Medio,
                    ConhecimentoEmMajento = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPHP = TipoNivelConhecimento.Medio,
                    ConhecimentoEmWordpress = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPython = TipoNivelConhecimento.Senior,
                    ConhecimentoEmRuby = TipoNivelConhecimento.Medio,
                    ConhecimentoEmSQLServer = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmMySql = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSalesforce = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPhotoshop = TipoNivelConhecimento.Medio,
                    ConhecimentoEmIllustrator = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSEO = TipoNivelConhecimento.Medio,
                    LinkCrud = "https://github.com/Peixer/Easy_Crud"
                },
                new Candidato()
                {
                    Email = "joaquim@gmail.com",
                    Nome = "Joaquim",
                    Skype = "joaquim",
                    Telefone = "33256969",
                    Linkedin = "https://www.linkedin.com/in/joaquim/",
                    Cidade = "Ascurra",
                    Estado = "SC",
                    Portfolio = "joaquim.peixer.com",
                    Disponibilidade = TipoDisponibilidade.FinaisDeSemana,
                    HorarioDeTrabalho = TipoHorarioDeTrabalho.Manha | TipoHorarioDeTrabalho.Noite |
                                        TipoHorarioDeTrabalho.Comercial,
                    PretensaoSalarial = 2000.00,
                    ConhecimentoEmIonic = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmAndroid = TipoNivelConhecimento.Senior,
                    ConhecimentoEmIOS = TipoNivelConhecimento.Senior,
                    ConhecimentoEmHtml = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmCss = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmBoostrap = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJQuery = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAngularJS = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmJava = TipoNivelConhecimento.Senior,
                    ConhecimentoEmAspNetMvc = TipoNivelConhecimento.Senior,
                    ConhecimentoEmC = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCPlusPlus = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCake = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmDJango = TipoNivelConhecimento.Medio,
                    ConhecimentoEmMajento = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPHP = TipoNivelConhecimento.Medio,
                    ConhecimentoEmWordpress = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPython = TipoNivelConhecimento.Senior,
                    ConhecimentoEmRuby = TipoNivelConhecimento.Medio,
                    ConhecimentoEmSQLServer = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmMySql = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSalesforce = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPhotoshop = TipoNivelConhecimento.Medio,
                    ConhecimentoEmIllustrator = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSEO = TipoNivelConhecimento.Medio,
                    LinkCrud = "https://github.com/Peixer/Easy_Crud"
                },
                new Candidato()
                {
                    Email = "Rafael@gmail.com",
                    Nome = "rafael",
                    Skype = "rafael",
                    Telefone = "33256969",
                    Linkedin = "https://www.linkedin.com/in/rafael/",
                    Cidade = "rio negrinho",
                    Estado = "SC",
                    Portfolio = "rafael.peixer.com",
                    Disponibilidade = TipoDisponibilidade.FinaisDeSemana | TipoDisponibilidade.MaisDeOitoHoras,
                    HorarioDeTrabalho = TipoHorarioDeTrabalho.Noite | TipoHorarioDeTrabalho.Comercial,
                    PretensaoSalarial = 1000.00,
                    ConhecimentoEmIonic = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmAndroid = TipoNivelConhecimento.Senior,
                    ConhecimentoEmIOS = TipoNivelConhecimento.Senior,
                    ConhecimentoEmHtml = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmCss = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmBoostrap = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJQuery = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAngularJS = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmJava = TipoNivelConhecimento.Senior,
                    ConhecimentoEmAspNetMvc = TipoNivelConhecimento.Senior,
                    ConhecimentoEmC = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCPlusPlus = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCake = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmDJango = TipoNivelConhecimento.Medio,
                    ConhecimentoEmMajento = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPHP = TipoNivelConhecimento.Medio,
                    ConhecimentoEmWordpress = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPython = TipoNivelConhecimento.Senior,
                    ConhecimentoEmRuby = TipoNivelConhecimento.Medio,
                    ConhecimentoEmSQLServer = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmMySql = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSalesforce = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPhotoshop = TipoNivelConhecimento.Medio,
                    ConhecimentoEmIllustrator = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSEO = TipoNivelConhecimento.Medio,
                    LinkCrud = "https://github.com/Peixer/Easy_Crud"
                },
                new Candidato()
                {
                    Email = "gjpeixer@gmail.com",
                    Nome = "Glaicon Peixer",
                    Skype = "glaiconsc",
                    Telefone = "33569250",
                    Linkedin = "https://www.linkedin.com/in/glaicon-peixer/",
                    Cidade = "Blumenau",
                    Estado = "SC",
                    Portfolio = "glaicon.peixer.com",
                    Disponibilidade = TipoDisponibilidade.AteOitoHoras | TipoDisponibilidade.MaisDeOitoHoras,
                    HorarioDeTrabalho = TipoHorarioDeTrabalho.Noite | TipoHorarioDeTrabalho.Madrugada |
                                        TipoHorarioDeTrabalho.Tarde,
                    PretensaoSalarial = 2.50,
                    ConhecimentoEmIonic = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAndroid = TipoNivelConhecimento.Medio,
                    ConhecimentoEmIOS = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmHtml = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmCss = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmBoostrap = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmJQuery = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAngularJS = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJava = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAspNetMvc = TipoNivelConhecimento.Senior,
                    ConhecimentoEmC = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCPlusPlus = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCake = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmDJango = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmMajento = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPHP = TipoNivelConhecimento.Medio,
                    ConhecimentoEmWordpress = TipoNivelConhecimento.Medio,
                    ConhecimentoEmPython = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmRuby = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSQLServer = TipoNivelConhecimento.Medio,
                    ConhecimentoEmMySql = TipoNivelConhecimento.Medio,
                    ConhecimentoEmSalesforce = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPhotoshop = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmIllustrator = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSEO = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmOutroFramework = "Laravel - Bom",
                    LinkCrud = "https://github.com/Peixer/Easy_Crud"
                },
                new Candidato()
                {
                    Email = "leticia@gmail.com",
                    Nome = "Leticia Pires",
                    Skype = "letpires",
                    Telefone = "33285459",
                    Linkedin = "https://www.linkedin.com/in/letpires/",
                    Cidade = "Blumenau",
                    Estado = "SC",
                    Portfolio = "letpires.peixer.com",
                    Disponibilidade = TipoDisponibilidade.AteSeisHoras | TipoDisponibilidade.AteQuatroHoras,
                    HorarioDeTrabalho = TipoHorarioDeTrabalho.Manha | TipoHorarioDeTrabalho.Tarde |
                                        TipoHorarioDeTrabalho.Noite,
                    PretensaoSalarial = 1222.50,
                    ConhecimentoEmIonic = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmAndroid = TipoNivelConhecimento.Senior,
                    ConhecimentoEmIOS = TipoNivelConhecimento.Senior,
                    ConhecimentoEmHtml = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmCss = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmBoostrap = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJQuery = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAngularJS = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJava = TipoNivelConhecimento.Senior,
                    ConhecimentoEmAspNetMvc = TipoNivelConhecimento.Senior,
                    ConhecimentoEmC = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCPlusPlus = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCake = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmDJango = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmMajento = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPHP = TipoNivelConhecimento.Senior,
                    ConhecimentoEmWordpress = TipoNivelConhecimento.Senior,
                    ConhecimentoEmPython = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmRuby = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSQLServer = TipoNivelConhecimento.Medio,
                    ConhecimentoEmMySql = TipoNivelConhecimento.Medio,
                    ConhecimentoEmSalesforce = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPhotoshop = TipoNivelConhecimento.Medio,
                    ConhecimentoEmIllustrator = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSEO = TipoNivelConhecimento.Medio,
                    LinkCrud = "https://github.com/Peixer/Easy_Crud"
                },
                new Candidato()
                {
                    Email = "lucas@gmail.com",
                    Nome = "Lucas",
                    Skype = "lukitas",
                    Telefone = "33256969",
                    Linkedin = "https://www.linkedin.com/in/lucas/",
                    Cidade = "Navegantes",
                    Estado = "SC",
                    Portfolio = "lucas.peixer.com",
                    Disponibilidade = TipoDisponibilidade.FinaisDeSemana | TipoDisponibilidade.AteQuatroHoras,
                    HorarioDeTrabalho = TipoHorarioDeTrabalho.Manha | TipoHorarioDeTrabalho.Noite,
                    PretensaoSalarial = 12000.00,
                    ConhecimentoEmIonic = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmAndroid = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmIOS = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmHtml = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmCss = TipoNivelConhecimento.Senior,
                    ConhecimentoEmBoostrap = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJQuery = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAngularJS = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmJava = TipoNivelConhecimento.Senior,
                    ConhecimentoEmAspNetMvc = TipoNivelConhecimento.Senior,
                    ConhecimentoEmC = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCPlusPlus = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCake = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmDJango = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmMajento = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPHP = TipoNivelConhecimento.Senior,
                    ConhecimentoEmWordpress = TipoNivelConhecimento.Senior,
                    ConhecimentoEmPython = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmRuby = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSQLServer = TipoNivelConhecimento.Medio,
                    ConhecimentoEmMySql = TipoNivelConhecimento.Senior,
                    ConhecimentoEmSalesforce = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPhotoshop = TipoNivelConhecimento.Medio,
                    ConhecimentoEmIllustrator = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSEO = TipoNivelConhecimento.Medio,
                    LinkCrud = "https://github.com/Peixer/Easy_Crud"
                },
                new Candidato()
                {
                    Email = "daniel@gmail.com",
                    Nome = "Daniel",
                    Skype = "DanielSC",
                    Telefone = "335978",
                    Linkedin = "https://www.linkedin.com/in/daniel/",
                    Cidade = "Indaial",
                    Estado = "SC",
                    Portfolio = "daniel.peixer.com",
                    Disponibilidade = TipoDisponibilidade.AteQuatroHoras,
                    HorarioDeTrabalho = TipoHorarioDeTrabalho.Madrugada | TipoHorarioDeTrabalho.Noite,
                    PretensaoSalarial = 5000.00,
                    ConhecimentoEmIonic = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmAndroid = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmIOS = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmHtml = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmCss = TipoNivelConhecimento.Senior,
                    ConhecimentoEmBoostrap = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJQuery = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAngularJS = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmJava = TipoNivelConhecimento.Senior,
                    ConhecimentoEmAspNetMvc = TipoNivelConhecimento.Senior,
                    ConhecimentoEmC = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCPlusPlus = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCake = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmDJango = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmMajento = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPHP = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmWordpress = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPython = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmRuby = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmSQLServer = TipoNivelConhecimento.Medio,
                    ConhecimentoEmMySql = TipoNivelConhecimento.Senior,
                    ConhecimentoEmSalesforce = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmPhotoshop = TipoNivelConhecimento.Medio,
                    ConhecimentoEmIllustrator = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSEO = TipoNivelConhecimento.Medio,
                    LinkCrud = "https://github.com/Peixer/Easy_Crud"
                },
                new Candidato()
                {
                    Email = "fernando@gmail.com",
                    Nome = "Fernando",
                    Skype = "fernandoNavega",
                    Telefone = "33257069",
                    Linkedin = "https://www.linkedin.com/in/fernando/",
                    Cidade = "Navegantes",
                    Estado = "SC",
                    Portfolio = "fernando.peixer.com",
                    Disponibilidade = TipoDisponibilidade.FinaisDeSemana,
                    HorarioDeTrabalho = TipoHorarioDeTrabalho.Manha | TipoHorarioDeTrabalho.Noite,
                    PretensaoSalarial = 12000.00,
                    ConhecimentoEmIonic = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmAndroid = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmIOS = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmHtml = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmCss = TipoNivelConhecimento.Medio,
                    ConhecimentoEmBoostrap = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJQuery = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAngularJS = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmJava = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAspNetMvc = TipoNivelConhecimento.Medio,
                    ConhecimentoEmC = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCPlusPlus = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCake = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmDJango = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmMajento = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPHP = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmWordpress = TipoNivelConhecimento.Senior,
                    ConhecimentoEmPython = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmRuby = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSQLServer = TipoNivelConhecimento.Medio,
                    ConhecimentoEmMySql = TipoNivelConhecimento.Senior,
                    ConhecimentoEmSalesforce = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPhotoshop = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmIllustrator = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSEO = TipoNivelConhecimento.Medio,
                    LinkCrud = "https://github.com/Peixer/Easy_Crud"
                },
                new Candidato()
                {
                    Email = "gjpeixer@gmail.com",
                    Nome = "Glaicon Peixer",
                    Skype = "glaiconsc",
                    Telefone = "33569250",
                    Linkedin = "https://www.linkedin.com/in/glaicon-peixer/",
                    Cidade = "Blumenau",
                    Estado = "SC",
                    Portfolio = "glaicon.peixer.com",
                    Disponibilidade = TipoDisponibilidade.AteOitoHoras | TipoDisponibilidade.MaisDeOitoHoras,
                    HorarioDeTrabalho = TipoHorarioDeTrabalho.Noite | TipoHorarioDeTrabalho.Madrugada |
                                        TipoHorarioDeTrabalho.Tarde,
                    PretensaoSalarial = 2.50,
                    ConhecimentoEmIonic = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAndroid = TipoNivelConhecimento.Medio,
                    ConhecimentoEmIOS = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmHtml = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmCss = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmBoostrap = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmJQuery = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAngularJS = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJava = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAspNetMvc = TipoNivelConhecimento.Senior,
                    ConhecimentoEmC = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCPlusPlus = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCake = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmDJango = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmMajento = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPHP = TipoNivelConhecimento.Medio,
                    ConhecimentoEmWordpress = TipoNivelConhecimento.Medio,
                    ConhecimentoEmPython = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmRuby = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSQLServer = TipoNivelConhecimento.Medio,
                    ConhecimentoEmMySql = TipoNivelConhecimento.Medio,
                    ConhecimentoEmSalesforce = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPhotoshop = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmIllustrator = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSEO = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmOutroFramework = "Laravel - Bom",
                    LinkCrud = "https://github.com/Peixer/Easy_Crud"
                },
                new Candidato()
                {
                    Email = "leticia@gmail.com",
                    Nome = "Leticia Pires",
                    Skype = "letpires",
                    Telefone = "33285459",
                    Linkedin = "https://www.linkedin.com/in/letpires/",
                    Cidade = "Blumenau",
                    Estado = "SC",
                    Portfolio = "letpires.peixer.com",
                    Disponibilidade = TipoDisponibilidade.AteSeisHoras | TipoDisponibilidade.AteQuatroHoras,
                    HorarioDeTrabalho = TipoHorarioDeTrabalho.Manha | TipoHorarioDeTrabalho.Tarde |
                                        TipoHorarioDeTrabalho.Noite,
                    PretensaoSalarial = 1222.50,
                    ConhecimentoEmIonic = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmAndroid = TipoNivelConhecimento.Senior,
                    ConhecimentoEmIOS = TipoNivelConhecimento.Senior,
                    ConhecimentoEmHtml = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmCss = TipoNivelConhecimento.Baixo,
                    ConhecimentoEmBoostrap = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJQuery = TipoNivelConhecimento.Medio,
                    ConhecimentoEmAngularJS = TipoNivelConhecimento.Medio,
                    ConhecimentoEmJava = TipoNivelConhecimento.Senior,
                    ConhecimentoEmAspNetMvc = TipoNivelConhecimento.Senior,
                    ConhecimentoEmC = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCPlusPlus = TipoNivelConhecimento.MuitoBaixo,
                    ConhecimentoEmCake = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmDJango = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmMajento = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPHP = TipoNivelConhecimento.Senior,
                    ConhecimentoEmWordpress = TipoNivelConhecimento.Senior,
                    ConhecimentoEmPython = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmRuby = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSQLServer = TipoNivelConhecimento.Medio,
                    ConhecimentoEmMySql = TipoNivelConhecimento.Medio,
                    ConhecimentoEmSalesforce = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmPhotoshop = TipoNivelConhecimento.Medio,
                    ConhecimentoEmIllustrator = TipoNivelConhecimento.Nenhum,
                    ConhecimentoEmSEO = TipoNivelConhecimento.Medio,
                    LinkCrud = "https://github.com/Peixer/Easy_Crud"
                }
            };
        }
    }
}